import turtle
t= turtle.Turtle()
length = int(input("길이를 입력하세요: "))
t.color("mediumpurple")
t.width(5)
t.forward(length)
t.left(90)
t.forward(length)
t.right(90)
t.forward(length)
t.right(90)
t.forward(length)
t.left(90)
t.forward(length)
